config/routes.rb
Rails.application.routes.draw do
  resources :buyer_locations
  resources :service_buyers
  resources :locations
  resources :buyers
  resources :leads,except: [:new, :create]
  resources :services
  resources :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/service.rb
class Service < ApplicationRecord

  has_many :service_buyers
  has_many :buyers, through: :service_buyers

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[ show edit update destroy ]

  # GET /services or /services.json
  def index
    @services = Service.all
  end

  # GET /services/1 or /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services or /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to service_url(@service), notice: "Service was successfully created." }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1 or /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to service_url(@service), notice: "Service was successfully updated." }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1 or /services/1.json
  def destroy
    @service.destroy

    respond_to do |format|
      format.html { redirect_to services_url, notice: "Service was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_params
      params.require(:service).permit(:name, :active)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_with(model: service) do |form| %>

  <%= render "shared/errors", object:service %>
  <div class="row">
    <div class="col-2">

    </div>
    <div class="col-2">

    </div>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.check_box :active %>
  </div>

  <div class="mt-2">
    <%= form.submit %>
  </div>
<% end %>

app/views/services/_service.html.erb
<div id="<%= dom_id service %>" class="m-5">
  <table class="table">
    <tr>
      <td><strong>Name</strong></td>
      <td><%= service.name %></td>
    </tr>
    <tr>
      <td><strong>Active</strong></td>
      <td><%= service.active %></td>
    </tr>
  </table>
</div>

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render "form", service: @service %>

<br>

<div>
  <%= link_to "Show this service", @service %> |
  <%= link_to "Back to services", services_path %>
</div>

app/views/services/index.html.erb
<p style="color: green"><%= notice %></p>



<div id="services" class="m-5">
  <h1>Services</h1>
  <table class="table">
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Active</th>
      <th>Actions</th>
    </tr>

    <% @services.each do |service| %>
      <tr>
        <td><%= link_to service.id, service %></td>
        <td> <%= service.name %> </td>
        <td> <%= service.active %> </td>
        <td>
          <%= link_to "Edit", edit_service_url(service), class: 'btn btn-warning btn-sm' %>
          <%= button_to "Delete", service, method: :delete, class: 'btn btn-danger btn-sm' %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= link_to "New service", new_service_path, class:'btn btn-success' %>

</div>

app/views/services/new.html.erb
<h1>New service</h1>

<%= render "form", service: @service %>

<br>

<div>
  <%= link_to "Back to services", services_path %>
</div>

app/views/services/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @service %>

<div>
  <%= link_to "Back to services", services_path %>
</div>