config/routes.rb
Rails.application.routes.draw do
  resources :buyer_locations
  resources :service_buyers
  resources :locations
  resources :buyers
  resources :leads,except: [:new, :create]
  resources :services
  resources :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/buyer_location.rb
class BuyerLocation < ApplicationRecord
  belongs_to :location
  belongs_to :buyer
end

app/controllers/buyer_locations_controller.rb
class BuyerLocationsController < ApplicationController
  before_action :set_buyer_location, only: %i[ show edit update destroy  ]

  # GET /buyer_locations or /buyer_locations.json
  def index
    @buyer_locations = BuyerLocation.all
  end

  # GET /buyer_locations/1 or /buyer_locations/1.json
  def show
  end

  def new
    @buyer_location = BuyerLocation.new
  end

  def create
    @buyer_location = BuyerLocation.new(buyer_location_params)

    respond_to do |format|
      if @buyer_location.save
        format.html { redirect_to buyer_location_url(@buyer_location), notice: "buyer_location was successfully created." }
        format.json { render :show, status: :created, buyer_location: @buyer_location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @buyer_location.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end
  def update
    respond_to do |format|
      if @buyer_location.update(buyer_location_params)
        format.html { redirect_to buyer_location_url(@buyer_location), notice: "buyer_location was successfully created." }
        format.json { render :show, status: :created, buyer_location: @buyer_location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @buyer_location.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @buyer_location.destroy

    respond_to do |format|
      format.html { redirect_to buyer_locations_url, notice: "buyer_location was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buyer_location
      @buyer_location = BuyerLocation.find(params[:id])
    end

    def buyer_location_params
      params.require(:buyer_location).permit(:location_id, :buyer_id, :active)
    end

end

app/helpers/buyer_locations_helper.rb
module BuyerLocationsHelper
end

app/views/buyer_locations/_buyer_location.html.erb
<div id="<%= dom_id buyer_location %>" class="m-5">

  <table class="table">
    <tr>
      <td><strong>Location</strong> </td>
      <td>   <%= Location.find(buyer_location.location_id)[:zip_code] %></td>
    </tr>
    <tr>
      <td><strong>Buyer</strong></td>
      <td><%= Buyer.find(buyer_location.buyer_id)[:name] %></td>
    </tr>
    <tr>
      <td><strong>Active</strong></td>
      <td><%= buyer_location.active %></td>
    </tr>
  </table>

</div>

app/views/buyer_locations/_form.html.erb
<%= form_with(model: @buyer_location) do |form| %>

  <%= render "shared/errors", object:@buyer_location %>

  <div class="row">
    <div class="col-2">
      <div>
        <%= form.label :location_id, style: "display: block" %>
        <% locations = {}%>
        <% Location.all.each do |location| %>
          <%  locations[location[:zip_code]]=location[:id] %>
        <% end %>
        <%= form.select :location_id, options_for_select(locations) %>
      </div>

      <div>
        <%= form.label :buyer_id, style: "display: block" %>
        <% buyers = {}%>
        <% Buyer.all.each do |buyer| %>
          <%  buyers[buyer[:name]]=buyer[:id] %>
        <% end %>
        <%= form.select :buyer_id, options_for_select(buyers) %>
      </div>
    </div>
    <div class="col-2">
      <div>
        <%= form.label :active, style: "display: block" %>
        <%= form.check_box :active %>
      </div>
    </div>
  </div>

  <div class="mt-2">
    <%= form.submit %>
  </div>

<% end %>

app/views/buyer_locations/edit.html.erb
<h1>Editing buyer location</h1>

<%= render "form", buyer_location: @buyer_location %>

<br>

<div>
  <%= link_to "Show this buyer location", @buyer_location %> |
  <%= link_to "Back to buyer locations", buyer_locations_path %>
</div>

app/views/buyer_locations/index.html.erb
<p style="color: green"><%= notice %></p>




<div id="buyer_locations" class="m-5">
  <h1>Buyer locations</h1>
  <table class="table">
    <tr>
      <th>Id</th>
      <th>Location</th>
      <th>Buyer</th>
      <th>Active</th>
      <th>Action</th>
    </tr>
    <% @buyer_locations.each do |buyer_location| %>
      <tr>
        <td> <%= link_to buyer_location.id, buyer_location %></td>
        <td> <%= Location.find(buyer_location.location_id)[:zip_code] %></td>
        <td> <%= Buyer.find(buyer_location.buyer_id)[:name] %></td>
        <td> <%=  buyer_location.active %> </td>
        <td>
          <%= link_to "Edit", edit_buyer_location_url(buyer_location), class: 'btn btn-warning btn-sm' %>
          <%= button_to "Delete", buyer_location, method: :delete, class: 'btn btn-danger btn-sm' %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= link_to "New buyer location", new_buyer_location_path, class:"btn btn-success" %>
</div>

app/views/buyer_locations/new.html.erb
<h1>New buyer location</h1>

<%= render "form", buyer_location: @buyer_location %>

<br>

<div>
  <%= link_to "Back to buyer locations", buyer_locations_path %>
</div>

app/views/buyer_locations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @buyer_location %>

<div>
  <%= link_to "Back to buyer locations", buyer_locations_path %>
</div>