config/routes.rb
Rails.application.routes.draw do
  resources :buyer_locations
  resources :service_buyers
  resources :locations
  resources :buyers
  resources :leads,except: [:new, :create]
  resources :services
  resources :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/admins/_admin.html.erb
<div id="<%= dom_id admin %>" class="m-5">

  <table class="table">
    <tr>
      <td><strong>Email</strong> </td>
      <td><%= admin.email %></td>
    </tr>
    <tr>
      <td><strong>Password</strong></td>
      <td><%= admin.password %></td>
    </tr>
    <tr>
      <td><strong>Name</strong></td>
      <td><%= admin.name %></td>
    </tr>
    <tr>
      <td><strong>Admin Type</strong></td>
      <td><%= admin.admin_type %></td>
    </tr>
  </table>

</div>

app/views/admins/_form.html.erb
<%= form_with(model: @admin) do |form| %>

  <%= render "shared/errors", object:@admin%>

  <div class="row">
    <div class="col-2">
      <div>
        <%= form.label :email, style: "display: block" %>
        <%= form.text_field :email %>
      </div>

      <div>
        <%= form.label :password, style: "display: block" %>
        <%= form.text_field :password %>
      </div>

      <div>
        <%= form.label :name, style: "display: block" %>
        <%= form.text_field :name %>
      </div>
    </div>
    <div class="col-2">
      <div>
        <%= form.label :admin_type, style: "display: block" %>
        <%= form.select :admin_type, Admin.admin_types.to_a %>
      </div>

    </div>
  </div>




  <div class="mt-2">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render "form", admin: @admin %>

<br>

<div>
  <%= link_to "Show this admin", @admin %> |
  <%= link_to "Back to admins", admins_path %>
</div>

app/views/admins/index.html.erb
<p style="color: green"><%= notice %></p>



<div id="admins" class="m-5">
  <h1>Admins</h1>
  <table class="table">
    <tr>
      <th>Id</th>
      <th>Email</th>
      <th>Password</th>
      <th>Name</th>
      <th>Admin type</th>
      <th>Action</th>
    </tr>

    <tr>
      <% @admins.each do |admin| %>
        <td><%= link_to admin.id, admin %></td>
        <td><%= admin.email %></td>
        <td><%= admin.password %></td>
        <td><%= admin.name %></td>
        <td><%= admin.admin_type %></td>
        <td>
          <%= link_to "Edit", edit_admin_url(admin), class: 'btn btn-warning btn-sm' %>
          <%= button_to "Delete", admin, method: :delete, class: 'btn btn-danger btn-sm' %>
        </td>
      <% end %>
    </tr>

  </table>
  <%= link_to "New Admin", new_admin_path, class:"btn btn-success" %>

</div>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render "form", admin: @admin %>

<br>

<div>
  <%= link_to "Back to admins", admins_path %>
</div>

app/views/admins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @admin %>

<div>
  <%= link_to "Back to admins", admins_path %>
</div>