config/routes.rb
Rails.application.routes.draw do
  resources :buyer_locations
  resources :service_buyers
  resources :locations
  resources :buyers
  resources :leads,except: [:new, :create]
  resources :services
  resources :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  has_many :service_buyers
  has_many :services, through: :service_buyers

  has_many :buyer_locations
  has_many :locations, through: :buyer_locations

  serialize :working_days, Array

end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  before_action :set_buyer, only: %i[ show edit update destroy ]


  # GET /buyers or /buyers.json
  def index
    @buyers = Buyer.all
  end

  # GET /buyers/1 or /buyers/1.json
  def show
  end

  # GET /buyers/new
  def new
    @buyer = Buyer.new
  end

  # GET /buyers/1/edit
  def edit
  end

  # POST /buyers or /buyers.json
  def create
    @buyer = Buyer.new(buyer_params)

    respond_to do |format|
      if @buyer.save
        format.html { redirect_to buyer_url(@buyer), notice: "Buyer was successfully created." }
        format.json { render :show, status: :created, location: @buyer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buyers/1 or /buyers/1.json
  def update
    respond_to do |format|
      puts '========='
      puts '========='
      puts buyer_params
      puts '========='
      puts '========='

      if @buyer.update(buyer_params)
        format.html { redirect_to buyer_url(@buyer), notice: "Buyer was successfully updated." }
        format.json { render :show, status: :ok, location: @buyer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buyers/1 or /buyers/1.json
  def destroy
    @buyer.destroy

    respond_to do |format|
      format.html { redirect_to buyers_url, notice: "Buyer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buyer
      @buyer = Buyer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def buyer_params
      temp_params=params.require(:buyer).permit(:name, :email, :phone_number, :active, :working_days => [])
      puts '==========='
      puts '==========='
      puts temp_params
      puts '==========='
      puts '==========='
      temp_params
    end
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/views/buyers/_buyer.html.erb
<div id="<%= dom_id buyer %>" class="m-5">

  <table class="table">
    <tr>
      <td><strong>Name</strong> </td>
      <td><%= buyer.name %></td>
    </tr>
    <tr>
      <td><strong>Email</strong></td>
      <td><%= buyer.email %></td>
    </tr>
    <tr>
      <td><strong>Phone Number</strong></td>
      <td><%= buyer.phone_number %></td>
    </tr>
    <tr>
      <td><strong>Working Days</strong></td>
      <td>
        <% day_names = WEEK_DAYS.to_a.map {|day| [day.last,day.first]}.to_h %>
        <%buyer.working_days.drop(1).each do |day| %>
          <ul>
            <li> <%= day_names[day] %></li>
          </ul>
        <% end %>
      </td>
    </tr>
    <tr>
      <td><strong>Active</strong></td>
      <td><%= buyer.active %></td>
    </tr>
  </table>


</div>

app/views/buyers/_form.html.erb
<%= form_with(model: buyer) do |form| %>

  <%= render "shared/errors", object:buyer %>

  <div class="row">
    <div class="col-2">
      <div>
        <%= form.label :name, style: "display: block" %>
        <%= form.text_field :name %>
      </div>

      <div>
        <%= form.label :email, style: "display: block" %>
        <%= form.text_field :email %>
      </div>

      <div>
        <%= form.label :phone_number, style: "display: block" %>
        <%= form.text_field :phone_number %>
      </div>
    </div>
    <div class="col-2">
      <div>
        <%= form.label :working_days, style: "display: block" %>
        <%= form.select :working_days, options_for_select(WEEK_DAYS.to_a), {}, {:multiple => true } %>

      </div>

      <div>
        <%= form.label :active, style: "display: block" %>
        <%= form.check_box :active %>
      </div>
    </div>
  </div>


  <div class="mt-2">
    <%= form.submit %>
  </div>
<% end %>

app/views/buyers/edit.html.erb
<h1>Editing buyer</h1>

<%= render "form", buyer: @buyer %>

<br>

<div>
  <%= link_to "Show this buyer", @buyer %> |
  <%= link_to "Back to buyers", buyers_path %>
</div>

app/views/buyers/index.html.erb
<p style="color: green"><%= notice %></p>


<div id="buyers"  class="m-5">

  <h1>Buyers</h1>
  <table class="table">
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Email</th>
      <th>Phone Number</th>
      <th>Working Days</th>
      <th>Active</th>
      <th>Actions</th>
    </tr>
    <% @buyers.each do |buyer| %>
      <tr>
        <td> <%= link_to buyer.id, buyer %></td>
        <td> <%= buyer.name %></td>
        <td> <%= buyer.email %></td>
        <td> <%=  buyer.phone_number %> </td>
        <td>  <% day_names = WEEK_DAYS.to_a.map {|day| [day.last,day.first]}.to_h %>
          <%buyer.working_days.drop(1).each do |day| %>
            <ul>
              <li> <%= day_names[day] %></li>
            </ul>
          <% end %>
        </td>
        <td> <%= buyer.active %></td>
        <td>
          <%= link_to "Edit", edit_buyer_url(buyer), class: 'btn btn-warning btn-sm' %>
          <%= button_to "Delete", buyer, method: :delete, class: 'btn btn-danger btn-sm' %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= link_to "New buyer", new_buyer_path, class:'btn btn-success' %>
</div>

app/views/buyers/new.html.erb
<h1>New buyer</h1>

<%= render "form", buyer: @buyer %>

<br>

<div>
  <%= link_to "Back to buyers", buyers_path %>
</div>

app/views/buyers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @buyer %>

<div>
  <%= link_to "Back to buyers", buyers_path %>
</div>